apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: naturenest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: omkarkhamkar/naturenest-mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: "image_gallery"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "pass"
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
