apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: upload-hpa
  namespace: naturenest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upload
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50




---



apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: watch-hpa
  namespace: naturenest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: watch
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
